language: groovy
jdk: oraclejdk8
sudo: false
branches:
  only:
  - beta
env:
  global:
  - secure: "y3wnnuBfJ1ej6bRGmeqEBYPq+impsJ2nAZ76VWJXMZHJVWgvqdLSjhTCgQsQeOf5VjFNWC2nLdGfEKjuvs6xI7cYNReKSyyURfz/iZmoIonxCovtyi9mONfgyidtmswCzYfZt44Kb5XiFYLzmqdvYPsrbx0TrIaDjOY8eWDwqORPlhB7vYLvKL9ObN3m6G8a+NyOdqZyDeJme+cnQDXw9R7XUGsyqZZ3SnKxRLIriwCM5Iy08EMhsIWfZ3dtCoYRvaKzdrnL2wfhr4cms6vYpB8t6VvA7w77X1BoHjvQObxir+TSXT5M1dfYrRVAPyCsHW45xHEWo2bGn8xqstDo9kXhhliXEH5aUEhZLI8Q3VEyqDdExX8/bxItUlVg07bYKdhkr8UmqZuWxqlNngzBee3/WfshirCYp/n4yMjEF7V07PJ+Eg2+WfUDbIEM3w8HSr58PKqqRGOyhH75TAkLIpA7qlsBfE/rb6zaHkdFeQ2p1nmY6c+ahKXHqXcTujsf8KUQJQ3TC4Zp9B5ROkrEvQSegQujkbyMOs1cKLycLcKGSpIzDZ1dGNHz4eJFZzDAL5Y5ZNhjYcnqN/TPygJj9SI9hLHBcxDoOnhhlOFD8G6qKtL9I5nf3jRAdfJbOCXKnNbW8bprzsDPgyTScl3uqC7/IiVcXJ4x6XQks3bm8u4="
  - secure: "HZe8ux8bZtw7gv4jIVpwJ8z1eUhxzSjLCm5razA0IF1m4IvRF2CWSOWl03chGd2eIvOdmYQnCBpxXcKvulQHBXM42NTUfa0u/x8Iyc3oJtFN7LtAeVpLtw0CyV+wU4o2CzuQx4QV4DXaYkf+NMF8ZLRaLWCdcFfM113ywDtwp2R+rJKEqmzZdTA3hv4zWuq31RGEDXEkW1k8d/OXBQB56JXWmh2/c2INCqngStsP0d+cA8i89Jj9ys1IzFWzsLeY7S3/68/n4hbSgAYFh3/iep7cIsd9y8K5JONLR8kFRnLff/2x0AqwG0IXKOGjzNh1ds3B1J+WEBvGIWKtq5oUQQ/kUT0ZPsYEy6UI67TFoJEXHvTp8pMjzwNtp8B342SLOcWmZcnLGJVFsgzREwEElLVtj3qjvt/S6IpW/0kXr5ZZ69HeCXo8VX9RZeBTS2v6mH+de/QYwYxV1b1kFsbFkcCdwRIwwiVS1gehvnsqnYiaPhD2ESYVN5YO7TQo167cCkHXQuikhGN0e+Zvxw8o5YTLtQwyw2D92Ro278zFr8bUq8UAg7G96aIcCte+7E6GNiD09kEb0Tsso+sV8fPRUwc/wnsP5jSrcQR7+TICnHDAKIbZ/JOsJ6/gZpKfLlZGpP/zFvlVNCthVBjcaL5qaEfsbs9P18WiiLB5f3NVM8U="
script:
- gradle deployBeta
